name: CI/CD TP5

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-analyze-docker:
    name: Build, Test, Analyze and Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build, Test and SonarCloud Analysis
        env:
          APP_MASTER_KEY: test_master_key_for_ci_only_32chars!
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify sonar:sonar
          -Dsonar.projectKey=anneso09_auth-tp5
          -Dsonar.organization=anneso09-1
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.qualitygate.wait=true

      - name: Build Docker image
        run: docker build -t cdwfs-auth-app .

      - name: Verify Docker image exists
        run: docker images cdwfs-auth-app