sonar.projectKey=anneso09_skillhub-ec06
sonar.organization=anneso09-1

# Analyse les deux backends
sonar.sources=skillhub-backend/app,skillhub-auth/src

# Exclusions
sonar.exclusions=**/vendor/**,**/node_modules/**,**/target/**,**/tests/**,**/.github/**
